#!/usr/bin/env python3
from argparse import ArgumentParser, Namespace
from subprocess import check_output


def main(arguments: Namespace):
    output = check_output([
        'ifstat',
        '-i',
        arguments.interface,
        arguments.delay,
        '1'
    ]).splitlines()[-1].decode()
    in_bytes, out_bytes = (float(value) for value in output.split())

    print('Traffic for {interface} -- Rx: {in_bytes} KB/s // Tx: {out_bytes} KB/s'.format(
        interface=arguments.interface,
        in_bytes=in_bytes,
        out_bytes=out_bytes))


if __name__ == '__main__':
    parser = ArgumentParser()
    parser.add_argument('-i', '--interface', required=True,
        help='Interface to messure (e.g. eth0)')
    parser.add_argument('-d', '--delay', default=60,
        help='Delay to measure in seconds. The average traffic over that period will be printed.')
    main(parser.parse_args())
